[workspace]
resolver = "2"
members = ["crates/pact-identity", "crates/pact-identity-wasm", "crates/pact"]

[workspace.package]
version = "0.3.5"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/pact-cloud/pact-identity"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
